site_name: Telemetry Platform
repo_url: https://github.com/pavlogutsa/telemetry-platform-demo
theme:
  name: material

nav:
  - Overview: docs/index.md
  - Vision & Scope: docs/01-vision-scope.md
  - Architecture: docs/02-architecture.md
  - Data & Messaging: docs/03-data-design.md
  - API:
      - Ingest API: docs/04-api/openapi-ingest.yaml
      - Device State API: docs/04-api/openapi-device-state.yaml
  - Infrastructure: docs/05-infrastructure.md
  - Testing: docs/06-testing-strategy.md
  - Observability: docs/07-observability.md
  - Security: docs/08-security.md
  - Release Roadmap: docs/09-release-roadmap.md
  - Future Notes: docs/10-future-notes.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.mermaid
