site_name: Telemetry Platform
repo_url: https://github.com/pavlogutsa/telemetry-platform-demo

theme:
  name: material

nav:
  - Overview: index.md
  - Vision & Scope: 01-vision-scope.md
  - Architecture: 02-architecture.md
  - Data & Messaging: 03-data-design.md
  - API:
      - Ingest API: 04-api/openapi-ingest.yaml
      - Device State API: 04-api/openapi-device-state.yaml
  - Specs:
      - Release 1 Spec: 11-release1-spec.md
  - Infrastructure: 05-infrastructure.md
  - Testing: 06-testing-strategy.md
  - Observability: 07-observability.md
  - Security: 08-security.md
  - Release Roadmap: 09-release-roadmap.md
  - Future Notes: 10-future-notes.md
  - Troubleshooting: 12-troubleshooting.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

use_directory_urls: false
