global:
  namespace: telemetry
  oracle:
    password: telemetry_pw
    user: telemetry
    jdbc_url: jdbc:oracle:thin:@oracle-db.telemetry.svc.cluster.local:1521/XEPDB1

agent-ingest-svc:
  image: agent-ingest-svc:release1
  replicas: 2

device-state-svc:
  image: device-state-svc:release1
  replicas: 1
  containerPort: 8081
  servicePort: 8080

ingress:
  host: telemetry.internal
