apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry-gateway
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host | default "telemetry.local" }}
      http:
        paths:
          - path: /api/telemetry
            pathType: Prefix
            backend:
              service:
                name: agent-ingest-svc
                port:
                  number: 8080
          - path: /api/devices
            pathType: Prefix
            backend:
              service:
                name: device-state-svc
                port:
                  number: 8080
